### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader

### ISSUE THREAD

**Issue by waclawthedev** [talsec/Free-RASP-Community#28]
One of our user has a crash arrived in Crashlytics:
```
Fatal Exception: java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xxx.XXX-vO2S2gINuBI7vZI7GQuEhw==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.XXX-vO2S2gINuBI7vZI7GQuEhw==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libsecurity.so"
```

Brand:Google
Model:Nexus 5X
Orientation:Portrait
RAM free: 1.33 GB
Disk free: 416.32 MB
Operating System
Version:Android 8.1.0
Orientation:Portrait
Rooted:No

Stacktrace:
```
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xxx.XXX-vO2S2gINuBI7vZI7GQuEhw==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.XXX-vO2S2gINuBI7vZI7GQuEhw==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libsecurity.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at com.aheaditec.talsec.security.a2.<clinit>(a2.java:11)
       at com.aheaditec.talsec.security.z1.<init>(z1.java:49)
       at com.aheaditec.talsec.security.z1.a(z1.java:50)
       at com.aheaditec.talsec_security.security.api.Talsec.start(Talsec.java:50)
       at com.xxx.XXX.XApplication.initTalsec(XApplication.java:50)
       at com.xxx.XXX.XApplication.onCreate(XApplication.java:102)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
       at android.app.ActivityThread.-wrap1()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
P.S. package name replaced with com.xxx.XXX in the text

**Comment by waclawthedev** [comment]
I have checked the logs. Seems like someone started app on x86 emulator :)
